"""Clinical alert engine service.

Alerts are generated by clinical rules (allergy conflicts, drug interactions,
critical lab/radiology values, abnormal vitals, fall risk, overdue tasks,
upcoming/missed follow-ups) and follow a guarded lifecycle:

    OPEN -> ACKNOWLEDGED -> RESOLVED
       +--------------> DISMISSED

Severities: INFO < LOW < MODERATE < HIGH < CRITICAL. Alerts never block a
clinical action by themselves — but the UI calls out CRITICAL/HIGH alerts at
the point of prescribing, ordering, and dispensing.
"""
from app import db
from app.models import ClinicalAlert
from app.utils import utcnow

SEVERITIES = ('INFO', 'LOW', 'MODERATE', 'HIGH', 'CRITICAL')
STATUSES = ('OPEN', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'DISMISSED')
ACTIVE_STATUSES = ('OPEN', 'ACKNOWLEDGED', 'IN_PROGRESS')
SEVERITY_WEIGHT = {s: i for i, s in enumerate(SEVERITIES)}

_ALERT_TYPE_COLORS = {
    'ALLERGY': 'danger', 'DRUG_INTERACTION': 'danger', 'DRUG_DISEASE': 'danger',
    'DUPLICATE_THERAPY': 'warning', 'CRITICAL_LAB': 'danger', 'CRITICAL_RADIOLOGY': 'warning',
    'ABNORMAL_VITALS': 'warning', 'FALL_RISK': 'warning', 'OVERDUE_TASK': 'warning',
    'EXPIRING_MEDICATION': 'warning', 'OVERDUE_FOLLOWUP': 'info',
    'MISSED_APPOINTMENT': 'info',
    'AI_FRACTURE_DETECTED': 'danger',
    'AI_MELANOMA_SUSPECTED': 'danger',
    'READMISSION_RISK': 'warning',
    'VACCINE_DUE': 'info',
    'UPCOMING_FOLLOWUP': 'info',
}


def alert_color(alert_type):
    return _ALERT_TYPE_COLORS.get(alert_type, 'info')


def _uid():
    """Current acting user id, or None when there is no request context."""
    try:
        from flask_login import current_user
        return current_user.id if current_user.is_authenticated else None
    except Exception:
        return None


def create_alert(patient_id, alert_type, title, message=None, severity='INFO',
                 source_type=None, source_id=None):
    """Persist a new clinical alert (status OPEN)."""
    if severity not in SEVERITIES:
        severity = 'INFO'
    alert = ClinicalAlert(
        patient_id=patient_id, alert_type=alert_type, title=title,
        message=message, severity=severity, status='OPEN',
        source_type=source_type, source_id=source_id,
    )
    db.session.add(alert)
    db.session.flush()
    return alert


def ensure_open_alert(patient_id, alert_type, severity='INFO', **kwargs):
    """Alerts should not duplicate: return the existing OPEN alert for the same
    patient+type+source, otherwise create a new one."""
    source_type = kwargs.pop('source_type', None)
    source_id = kwargs.pop('source_id', None)
    q = ClinicalAlert.query.filter_by(
        patient_id=patient_id, alert_type=alert_type, status='OPEN')
    if source_type is not None:
        q = q.filter_by(source_type=source_type)
    if source_id is not None:
        q = q.filter_by(source_id=source_id)
    existing = q.first()
    if existing is not None:
        if severity and SEVERITY_WEIGHT[severity] > SEVERITY_WEIGHT[existing.severity]:
            existing.severity = severity
        return existing
    return create_alert(patient_id, alert_type, severity=severity,
                        source_type=source_type, source_id=source_id, **kwargs)


def _transition(alert, new_status):
    if new_status not in STATUSES:
        raise ValueError(f'Unknown alert status: {new_status}')
    valid = {
        'OPEN': {'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'DISMISSED'},
        'ACKNOWLEDGED': {'IN_PROGRESS', 'RESOLVED', 'DISMISSED'},
        'IN_PROGRESS': {'RESOLVED', 'DISMISSED'},
        'RESOLVED': set(),
        'DISMISSED': set(),
    }
    if new_status not in valid.get(alert.status, set()):
        raise ValueError(f'Cannot move alert from {alert.status} to {new_status}')
    return True


def acknowledge(alert):
    """Mark an OPEN alert as acknowledged by the acting user."""
    _transition(alert, 'ACKNOWLEDGED')
    alert.status = 'ACKNOWLEDGED'
    alert.acknowledged_by = _uid()
    alert.acknowledged_at = utcnow()


def start_progress(alert):
    """The responsible clinician is acting on the alert."""
    _transition(alert, 'IN_PROGRESS')
    if alert.acknowledged_at is None:
        alert.acknowledged_by = _uid()
        alert.acknowledged_at = utcnow()
    alert.status = 'IN_PROGRESS'
    alert.started_by = _uid()
    alert.started_at = utcnow()


def resolve(alert, note=None, action_taken=None):
    """Close an active alert with a resolution note and the documented action."""
    _transition(alert, 'RESOLVED')
    if alert.severity in ('HIGH', 'CRITICAL') and not (action_taken or note):
        raise ValueError('Document the action taken before resolving a high-severity alert.')
    if alert.acknowledged_at is None:
        alert.acknowledged_by = _uid()
        alert.acknowledged_at = utcnow()
    alert.status = 'RESOLVED'
    alert.resolved_by = _uid()
    alert.resolved_at = utcnow()
    alert.resolved_note = note
    if action_taken:
        alert.action_taken = action_taken


def dismiss(alert, note=None):
    """Indicate an alert was considered and judged not actionable. A reason is
    mandatory for HIGH/CRITICAL alerts."""
    _transition(alert, 'DISMISSED')
    if alert.severity in ('HIGH', 'CRITICAL') and not (note or '').strip():
        raise ValueError('A reason is required to dismiss a high-severity alert.')
    alert.status = 'DISMISSED'
    alert.resolved_by = _uid()
    alert.resolved_at = utcnow()
    alert.resolved_note = note


def escalation_thresholds():
    """Minutes an unacknowledged alert may stay OPEN per severity
    (``ALERT_ESCALATION_MINUTES`` in config; never a hard-coded policy)."""
    from flask import current_app, has_app_context
    default = {'CRITICAL': 30, 'HIGH': 120}
    if has_app_context():
        cfg = current_app.config.get('ALERT_ESCALATION_MINUTES') or {}
        return {**default, **{k: int(v) for k, v in cfg.items()}}
    return default


def escalate_overdue(now=None):
    """Escalate OPEN critical/high alerts that nobody acknowledged within the
    configured window: notify supervisors and the patient's care team, open an
    escalation task, and stamp the alert. Idempotent (one escalation per
    alert). Returns the list of escalated alerts."""
    from datetime import timedelta
    from app.services import tasks as task_svc
    from app.services.notifications import notify_role, notify_users, care_team_user_ids
    now = now or utcnow()
    escalated = []
    for severity, minutes in escalation_thresholds().items():
        cutoff = now - timedelta(minutes=minutes)
        rows = (ClinicalAlert.query
                .filter(ClinicalAlert.status == 'OPEN',
                        ClinicalAlert.severity == severity,
                        ClinicalAlert.escalated_at.is_(None),
                        ClinicalAlert.created_at <= cutoff).all())
        for alert in rows:
            alert.escalated_at = now
            alert.escalation_note = (f'Unacknowledged for more than {minutes} min; '
                                     f'escalated to supervisors and the care team.')
            title = f'ESCALATION: unacknowledged {severity.lower()} alert'
            body = (f'Alert #{alert.id} "{alert.title}" for patient '
                    f'#{alert.patient_id} has had no acknowledgement for {minutes} minutes.')
            notify_role('Admin', title, body, notification_type='critical',
                        entity_type='clinical_alert', entity_id=alert.id)
            team = [uid for uid in care_team_user_ids(alert.patient_id) if uid != alert.assigned_to]
            if team:
                notify_users(team, title, body, notification_type='critical',
                             entity_type='clinical_alert', entity_id=alert.id)
            task_svc.create_task(
                title=f'Escalated alert #{alert.id}: {alert.title}',
                description=body, task_type='ESCALATION', department='Clinical Governance',
                patient_id=alert.patient_id, assigned_role='Admin', priority='URGENT',
                related_resource_type='clinical_alert', related_resource_id=alert.id)
            escalated.append(alert)
    return escalated


def open_alerts_for_patient(patient_id):
    return (ClinicalAlert.query
            .filter(ClinicalAlert.patient_id == patient_id,
                    ClinicalAlert.status.in_(ACTIVE_STATUSES))
            .order_by(ClinicalAlert.created_at.desc()).all())


def most_severe_open(patient_id):
    """Highest-severity open alert for a patient, or None."""
    alerts = ClinicalAlert.query.filter_by(
        patient_id=patient_id, status='OPEN').all()
    if not alerts:
        return None
    return max(alerts, key=lambda a: SEVERITY_WEIGHT.get(a.severity, 0))