"""Clinical alert engine service.

Alerts are generated by clinical rules (allergy conflicts, drug interactions,
critical lab/radiology values, abnormal vitals, fall risk, overdue tasks,
upcoming/missed follow-ups) and follow a guarded lifecycle:

    OPEN -> ACKNOWLEDGED -> RESOLVED
       +--------------> DISMISSED

Severities: INFO < LOW < MODERATE < HIGH < CRITICAL. Alerts never block a
clinical action by themselves — but the UI calls out CRITICAL/HIGH alerts at
the point of prescribing, ordering, and dispensing.
"""
from app import db
from app.models import ClinicalAlert
from app.utils import utcnow

SEVERITIES = ('INFO', 'LOW', 'MODERATE', 'HIGH', 'CRITICAL')
STATUSES = ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED')
SEVERITY_WEIGHT = {s: i for i, s in enumerate(SEVERITIES)}

_ALERT_TYPE_COLORS = {
    'ALLERGY': 'danger', 'DRUG_INTERACTION': 'danger', 'DRUG_DISEASE': 'danger',
    'DUPLICATE_THERAPY': 'warning', 'CRITICAL_LAB': 'danger', 'CRITICAL_RADIOLOGY': 'warning',
    'ABNORMAL_VITALS': 'warning', 'FALL_RISK': 'warning', 'OVERDUE_TASK': 'warning',
    'EXPIRING_MEDICATION': 'warning', 'OVERDUE_FOLLOWUP': 'info',
    'MISSED_APPOINTMENT': 'info',
    'AI_FRACTURE_DETECTED': 'danger',
    'AI_MELANOMA_SUSPECTED': 'danger',
    'READMISSION_RISK': 'warning',
    'VACCINE_DUE': 'info',
    'UPCOMING_FOLLOWUP': 'info',
}


def alert_color(alert_type):
    return _ALERT_TYPE_COLORS.get(alert_type, 'info')


def _uid():
    """Current acting user id, or None when there is no request context."""
    try:
        from flask_login import current_user
        return current_user.id if current_user.is_authenticated else None
    except Exception:
        return None


def create_alert(patient_id, alert_type, title, message=None, severity='INFO',
                 source_type=None, source_id=None):
    """Persist a new clinical alert (status OPEN)."""
    if severity not in SEVERITIES:
        severity = 'INFO'
    alert = ClinicalAlert(
        patient_id=patient_id, alert_type=alert_type, title=title,
        message=message, severity=severity, status='OPEN',
        source_type=source_type, source_id=source_id,
    )
    db.session.add(alert)
    db.session.flush()
    return alert


def ensure_open_alert(patient_id, alert_type, severity='INFO', **kwargs):
    """Alerts should not duplicate: return the existing OPEN alert for the same
    patient+type+source, otherwise create a new one."""
    source_type = kwargs.pop('source_type', None)
    source_id = kwargs.pop('source_id', None)
    q = ClinicalAlert.query.filter_by(
        patient_id=patient_id, alert_type=alert_type, status='OPEN')
    if source_type is not None:
        q = q.filter_by(source_type=source_type)
    if source_id is not None:
        q = q.filter_by(source_id=source_id)
    existing = q.first()
    if existing is not None:
        if severity and SEVERITY_WEIGHT[severity] > SEVERITY_WEIGHT[existing.severity]:
            existing.severity = severity
        return existing
    return create_alert(patient_id, alert_type, severity=severity,
                        source_type=source_type, source_id=source_id, **kwargs)


def _transition(alert, new_status):
    if new_status not in STATUSES:
        raise ValueError(f'Unknown alert status: {new_status}')
    valid = {
        'OPEN': {'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED'},
        'ACKNOWLEDGED': {'RESOLVED', 'DISMISSED'},
        'RESOLVED': set(),
        'DISMISSED': set(),
    }
    if new_status not in valid.get(alert.status, set()):
        raise ValueError(f'Cannot move alert from {alert.status} to {new_status}')
    return True


def acknowledge(alert):
    """Mark an OPEN alert as acknowledged by the acting user."""
    _transition(alert, 'ACKNOWLEDGED')
    alert.status = 'ACKNOWLEDGED'
    alert.acknowledged_by = _uid()
    alert.acknowledged_at = utcnow()


def resolve(alert, note=None):
    """Close an OPEN/ACKNOWLEDGED alert with a resolution note."""
    _transition(alert, 'RESOLVED')
    alert.status = 'RESOLVED'
    alert.resolved_by = _uid()
    alert.resolved_at = utcnow()
    alert.resolved_note = note


def dismiss(alert, note=None):
    """Indicate an alert was considered and judged not actionable."""
    _transition(alert, 'DISMISSED')
    alert.status = 'DISMISSED'
    alert.resolved_by = _uid()
    alert.resolved_at = utcnow()
    alert.resolved_note = note


def open_alerts_for_patient(patient_id):
    return (ClinicalAlert.query
            .filter(ClinicalAlert.patient_id == patient_id,
                    ClinicalAlert.status.in_(('OPEN', 'ACKNOWLEDGED')))
            .order_by(ClinicalAlert.created_at.desc()).all())


def most_severe_open(patient_id):
    """Highest-severity open alert for a patient, or None."""
    alerts = ClinicalAlert.query.filter_by(
        patient_id=patient_id, status='OPEN').all()
    if not alerts:
        return None
    return max(alerts, key=lambda a: SEVERITY_WEIGHT.get(a.severity, 0))