"""Granular, record-level permission catalog for iHIS Core.

The system the project is moving toward is:

    User -> Role -> Permissions -> Resource -> (Patient / Department / Specialty)

Instead of checking a role name on a page, routes should check a *permission*
on a *record type*, with ownership/specialty as an additional gate. This module
defines the canonical permission names and seeds them onto the matching roles.

Permission naming convention:  <RESOURCE>_<ACTION>
Actions: VIEW, CREATE, EDIT, VERIFY, SIGN, AMEND, DISPENSE, DELETE, MANAGE
"""

# ---- Patients / demographics ----
PATIENT_VIEW = 'PATIENT_VIEW'
PATIENT_CREATE = 'PATIENT_CREATE'
PATIENT_EDIT = 'PATIENT_EDIT'

# ---- Medical records (doctor-owned) ----
MEDICAL_RECORD_VIEW = 'MEDICAL_RECORD_VIEW'
MEDICAL_RECORD_CREATE = 'MEDICAL_RECORD_CREATE'
MEDICAL_RECORD_EDIT = 'MEDICAL_RECORD_EDIT'
MEDICAL_RECORD_SIGN = 'MEDICAL_RECORD_SIGN'
MEDICAL_RECORD_AMEND = 'MEDICAL_RECORD_AMEND'

# ---- Lab ----
LAB_ORDER_VIEW = 'LAB_ORDER_VIEW'
LAB_ORDER_CREATE = 'LAB_ORDER_CREATE'
LAB_RESULT_VIEW = 'LAB_RESULT_VIEW'
LAB_RESULT_CREATE = 'LAB_RESULT_CREATE'
LAB_RESULT_EDIT = 'LAB_RESULT_EDIT'
LAB_RESULT_VERIFY = 'LAB_RESULT_VERIFY'
LAB_RESULT_AMEND = 'LAB_RESULT_AMEND'

# ---- Radiology ----
RADIOLOGY_ORDER_VIEW = 'RADIOLOGY_ORDER_VIEW'
RADIOLOGY_ORDER_CREATE = 'RADIOLOGY_ORDER_CREATE'
RADIOLOGY_STUDY_VIEW = 'RADIOLOGY_STUDY_VIEW'
RADIOLOGY_VIEW = 'RADIOLOGY_VIEW'
RADIOLOGY_CREATE = 'RADIOLOGY_CREATE'
RADIOLOGY_EDIT = 'RADIOLOGY_EDIT'
RADIOLOGY_SIGN = 'RADIOLOGY_SIGN'
RADIOLOGY_AMEND = 'RADIOLOGY_AMEND'

# ---- Prescriptions ----
PRESCRIPTION_VIEW = 'PRESCRIPTION_VIEW'
PRESCRIPTION_CREATE = 'PRESCRIPTION_CREATE'
PRESCRIPTION_EDIT = 'PRESCRIPTION_EDIT'
PRESCRIPTION_CANCEL = 'PRESCRIPTION_CANCEL'
PRESCRIPTION_DISPENSE = 'PRESCRIPTION_DISPENSE'

# ---- Pharmacy inventory ----
PHARMACY_INVENTORY_VIEW = 'PHARMACY_INVENTORY_VIEW'
PHARMACY_INVENTORY_CREATE = 'PHARMACY_INVENTORY_CREATE'
PHARMACY_INVENTORY_EDIT = 'PHARMACY_INVENTORY_EDIT'
PHARMACY_STOCK_ADJUST = 'PHARMACY_STOCK_ADJUST'
INVENTORY_MANAGE = 'INVENTORY_MANAGE'

# ---- Document management ----
PATIENT_DOCUMENT_VIEW = 'PATIENT_DOCUMENT_VIEW'
PATIENT_DOCUMENT_UPLOAD = 'PATIENT_DOCUMENT_UPLOAD'
PATIENT_DOCUMENT_DELETE = 'PATIENT_DOCUMENT_DELETE'

# ---- Nursing ----
VITALS_VIEW = 'VITALS_VIEW'
VITALS_CREATE = 'VITALS_CREATE'
VITALS_EDIT = 'VITALS_EDIT'
NURSING_NOTE_CREATE = 'NURSING_NOTE_CREATE'
CARE_PLAN_CREATE = 'CARE_PLAN_CREATE'
CARE_PLAN_EDIT = 'CARE_PLAN_EDIT'
MEDICATION_ADMIN = 'MEDICATION_ADMIN'
INTAKE_OUTPUT_RECORD = 'INTAKE_OUTPUT_RECORD'

# ---- Dentistry ----
DENTAL_RECORD_VIEW = 'DENTAL_RECORD_VIEW'
DENTAL_RECORD_CREATE = 'DENTAL_RECORD_CREATE'
DENTAL_RECORD_EDIT = 'DENTAL_RECORD_EDIT'

# ---- Physiotherapy ----
PHYSIO_ASSESSMENT_VIEW = 'PHYSIO_ASSESSMENT_VIEW'
PHYSIO_ASSESSMENT_CREATE = 'PHYSIO_ASSESSMENT_CREATE'
PHYSIO_ASSESSMENT_EDIT = 'PHYSIO_ASSESSMENT_EDIT'

# ---- Reports / audit / system ----
REPORT_VIEW = 'REPORT_VIEW'
REPORT_EXPORT = 'REPORT_EXPORT'
AUDIT_VIEW = 'AUDIT_VIEW'
ADMIN_MANAGE_USERS = 'ADMIN_MANAGE_USERS'
ADMIN_MANAGE_ROLES = 'ADMIN_MANAGE_ROLES'
ADMIN_MANAGE_PERMISSIONS = 'ADMIN_MANAGE_PERMISSIONS'

# ---- Billing ----
BILL_VIEW = 'BILL_VIEW'
BILL_CREATE = 'BILL_CREATE'
BILL_EDIT = 'BILL_EDIT'
BILL_VOID = 'BILL_VOID'
PAYMENT_RECORD = 'PAYMENT_RECORD'
SERVICE_CATALOG_MANAGE = 'SERVICE_CATALOG_MANAGE'

# ---- Admissions & Beds ----
ADMISSION_VIEW = 'ADMISSION_VIEW'
ADMISSION_CREATE = 'ADMISSION_CREATE'
ADMISSION_DISCHARGE = 'ADMISSION_DISCHARGE'
BED_MANAGE = 'BED_MANAGE'

# ---- AI decision support ----
AI_USE = 'AI_USE'
MEDICATION_REVIEW = 'MEDICATION_REVIEW'
DRUG_INTERACTION = 'DRUG_INTERACTION'
AI_IMAGE_ANALYSIS = 'AI_IMAGE_ANALYSIS'

# ---- Timeline & alerts ----
TIMELINE_VIEW = 'TIMELINE_VIEW'
ALERT_VIEW = 'ALERT_VIEW'
ALERT_ACK = 'ALERT_ACK'
ALERTS_MANAGE = 'ALERTS_MANAGE'
SEARCH_GLOBAL = 'SEARCH_GLOBAL'

# ---- Structured clinical records ----
ALLERGY_VIEW = 'ALLERGY_VIEW'
ALLERGY_CREATE = 'ALLERGY_CREATE'
ALLERGY_EDIT = 'ALLERGY_EDIT'
PROBLEM_VIEW = 'PROBLEM_VIEW'
PROBLEM_CREATE = 'PROBLEM_CREATE'
PROBLEM_EDIT = 'PROBLEM_EDIT'
IMMUNIZATION_VIEW = 'IMMUNIZATION_VIEW'
IMMUNIZATION_CREATE = 'IMMUNIZATION_CREATE'
FOLLOWUP_CREATE = 'FOLLOWUP_CREATE'
FOLLOWUP_VIEW = 'FOLLOWUP_VIEW'
FOLLOWUP_COMPLETE = 'FOLLOWUP_COMPLETE'

# ---- Medication reconciliation & interventions ----
RECONCILIATION_VIEW = 'RECONCILIATION_VIEW'
RECONCILIATION_CREATE = 'RECONCILIATION_CREATE'
RECONCILIATION_COMPLETE = 'RECONCILIATION_COMPLETE'
INTERVENTION_CREATE = 'INTERVENTION_CREATE'
INTERVENTION_VIEW = 'INTERVENTION_VIEW'
INTERVENTION_RESPOND = 'INTERVENTION_RESPOND'

# ---- Nursing risk assessment ----
NURSING_RISK_VIEW = 'NURSING_RISK_VIEW'
NURSING_RISK_CREATE = 'NURSING_RISK_CREATE'

# ---- Order sets / templates / reminders / inbox / summary ----
ORDER_SET_VIEW = 'ORDER_SET_VIEW'
ORDER_SET_CREATE = 'ORDER_SET_CREATE'
ORDER_SET_EDIT = 'ORDER_SET_EDIT'
TEMPLATE_VIEW = 'TEMPLATE_VIEW'
TEMPLATE_CREATE = 'TEMPLATE_CREATE'
TEMPLATE_EDIT = 'TEMPLATE_EDIT'
INBOX_VIEW = 'INBOX_VIEW'
RESULT_ACK = 'RESULT_ACK'
REMINDER_VIEW = 'REMINDER_VIEW'
REMINDER_ACK = 'REMINDER_ACK'
CLINICAL_SUMMARY_VIEW = 'CLINICAL_SUMMARY_VIEW'

# Map each permission to the role(s) that should hold it by default.
ROLE_PERMISSIONS = {
    'Doctor': [
        PATIENT_VIEW, MEDICAL_RECORD_VIEW, MEDICAL_RECORD_CREATE, MEDICAL_RECORD_EDIT,
        MEDICAL_RECORD_SIGN, MEDICAL_RECORD_AMEND,
        LAB_ORDER_VIEW, LAB_ORDER_CREATE, LAB_RESULT_VIEW,
        RADIOLOGY_ORDER_VIEW, RADIOLOGY_ORDER_CREATE, RADIOLOGY_STUDY_VIEW, RADIOLOGY_VIEW,
        PRESCRIPTION_VIEW, PRESCRIPTION_CREATE, PRESCRIPTION_EDIT, PRESCRIPTION_CANCEL,
        ADMISSION_VIEW, ADMISSION_DISCHARGE,
        AI_USE, MEDICATION_REVIEW, DRUG_INTERACTION, AI_IMAGE_ANALYSIS,
        TIMELINE_VIEW, ALERT_VIEW, ALERT_ACK, SEARCH_GLOBAL,
        ALLERGY_VIEW, ALLERGY_CREATE, ALLERGY_EDIT,
        PROBLEM_VIEW, PROBLEM_CREATE, PROBLEM_EDIT,
        IMMUNIZATION_VIEW, IMMUNIZATION_CREATE,
        FOLLOWUP_CREATE, FOLLOWUP_VIEW, FOLLOWUP_COMPLETE,
        RECONCILIATION_VIEW, INTERVENTION_VIEW, INTERVENTION_RESPOND,
        ORDER_SET_VIEW, ORDER_SET_CREATE, ORDER_SET_EDIT,
        TEMPLATE_VIEW, TEMPLATE_CREATE, TEMPLATE_EDIT,
        INBOX_VIEW, RESULT_ACK, REMINDER_VIEW, REMINDER_ACK,
        CLINICAL_SUMMARY_VIEW,
    ],
    'LabTechnician': [
        PATIENT_VIEW, LAB_ORDER_VIEW, LAB_RESULT_VIEW, LAB_RESULT_CREATE, LAB_RESULT_EDIT,
        LAB_RESULT_VERIFY, LAB_RESULT_AMEND, AI_USE,
        TIMELINE_VIEW, SEARCH_GLOBAL,
    ],
    'Radiologist': [
        PATIENT_VIEW, RADIOLOGY_ORDER_VIEW, RADIOLOGY_STUDY_VIEW, RADIOLOGY_VIEW,
        RADIOLOGY_CREATE, RADIOLOGY_EDIT, RADIOLOGY_SIGN, RADIOLOGY_AMEND,
        AI_USE, AI_IMAGE_ANALYSIS,
        TIMELINE_VIEW, ALERT_VIEW, SEARCH_GLOBAL, INBOX_VIEW,
    ],
    # The technologist runs the study (schedule / arrival / acquisition /
    # images / dose) but never authors or signs the diagnostic report.
    'RadiologyTechnician': [
        PATIENT_VIEW, RADIOLOGY_ORDER_VIEW, RADIOLOGY_STUDY_VIEW, RADIOLOGY_VIEW,
        AI_USE, AI_IMAGE_ANALYSIS, TIMELINE_VIEW, SEARCH_GLOBAL,
    ],
    'Pharmacist': [
        PATIENT_VIEW, PRESCRIPTION_VIEW, PRESCRIPTION_DISPENSE,
        PHARMACY_INVENTORY_VIEW, PHARMACY_INVENTORY_CREATE, PHARMACY_INVENTORY_EDIT,
        PHARMACY_STOCK_ADJUST, INVENTORY_MANAGE,
        LAB_RESULT_VIEW, AI_USE, MEDICATION_REVIEW, DRUG_INTERACTION,
        TIMELINE_VIEW, ALERT_VIEW, ALERT_ACK, SEARCH_GLOBAL,
        ALLERGY_VIEW, PROBLEM_VIEW,
        RECONCILIATION_VIEW, RECONCILIATION_CREATE, RECONCILIATION_COMPLETE,
        INTERVENTION_CREATE, INTERVENTION_VIEW,
    ],
    'Nurse': [
        PATIENT_VIEW, MEDICAL_RECORD_VIEW, LAB_RESULT_VIEW, RADIOLOGY_VIEW,
        PRESCRIPTION_VIEW, VITALS_VIEW, VITALS_CREATE, VITALS_EDIT, NURSING_NOTE_CREATE,
        CARE_PLAN_CREATE, CARE_PLAN_EDIT, MEDICATION_ADMIN, INTAKE_OUTPUT_RECORD,
        ADMISSION_VIEW, AI_USE, MEDICATION_REVIEW, DRUG_INTERACTION,
        TIMELINE_VIEW, ALERT_VIEW, ALERT_ACK, SEARCH_GLOBAL,
        ALLERGY_VIEW, ALLERGY_CREATE, PROBLEM_VIEW, IMMUNIZATION_VIEW,
        FOLLOWUP_CREATE, FOLLOWUP_VIEW, FOLLOWUP_COMPLETE,
        RECONCILIATION_VIEW, INTERVENTION_VIEW,
        NURSING_RISK_VIEW, NURSING_RISK_CREATE,
    ],
    'Receptionist': [
        PATIENT_VIEW, PATIENT_CREATE, PATIENT_EDIT,
        BILL_VIEW, BILL_CREATE, BILL_EDIT, PAYMENT_RECORD,
        ADMISSION_VIEW, ADMISSION_CREATE,
        TIMELINE_VIEW, SEARCH_GLOBAL,
        ALLERGY_VIEW, ALLERGY_CREATE, PROBLEM_VIEW, IMMUNIZATION_VIEW,
    ],
    'Cashier': [
        PATIENT_VIEW, BILL_VIEW, BILL_EDIT, PAYMENT_RECORD,
        TIMELINE_VIEW, SEARCH_GLOBAL,
    ],
    'Dentist': [
        PATIENT_VIEW, DENTAL_RECORD_VIEW, DENTAL_RECORD_CREATE, DENTAL_RECORD_EDIT,
        RADIOLOGY_VIEW, LAB_RESULT_VIEW, AI_USE, AI_IMAGE_ANALYSIS, DRUG_INTERACTION,
        TIMELINE_VIEW, ALERT_VIEW, ALERT_ACK, SEARCH_GLOBAL,
        ALLERGY_VIEW, ALLERGY_CREATE, PROBLEM_VIEW, PROBLEM_CREATE,
        IMMUNIZATION_VIEW, FOLLOWUP_CREATE, FOLLOWUP_VIEW, FOLLOWUP_COMPLETE,
        RECONCILIATION_VIEW, INTERVENTION_VIEW, INTERVENTION_RESPOND,
    ],
    'Physiotherapist': [
        PATIENT_VIEW, PHYSIO_ASSESSMENT_VIEW, PHYSIO_ASSESSMENT_CREATE, PHYSIO_ASSESSMENT_EDIT,
        RADIOLOGY_VIEW, LAB_RESULT_VIEW, AI_USE,
        TIMELINE_VIEW, ALERT_VIEW, ALERT_ACK, SEARCH_GLOBAL,
        ALLERGY_VIEW, PROBLEM_VIEW, FOLLOWUP_CREATE, FOLLOWUP_VIEW, FOLLOWUP_COMPLETE,
    ],
    'Admin': [
        PATIENT_VIEW, PATIENT_EDIT, MEDICAL_RECORD_VIEW, LAB_RESULT_VIEW, RADIOLOGY_VIEW,
        PRESCRIPTION_VIEW, INVENTORY_MANAGE,
        MEDICATION_ADMIN, INTAKE_OUTPUT_RECORD,
        BILL_VIEW, BILL_CREATE, BILL_EDIT, BILL_VOID, PAYMENT_RECORD, SERVICE_CATALOG_MANAGE,
        ADMISSION_VIEW, ADMISSION_CREATE, ADMISSION_DISCHARGE, BED_MANAGE,
        REPORT_VIEW, REPORT_EXPORT, ADMIN_MANAGE_USERS,
        AI_USE, MEDICATION_REVIEW, DRUG_INTERACTION, AI_IMAGE_ANALYSIS,
        TIMELINE_VIEW, ALERT_VIEW, ALERT_ACK, ALERTS_MANAGE, SEARCH_GLOBAL,
        ALLERGY_VIEW, ALLERGY_CREATE, ALLERGY_EDIT,
        PROBLEM_VIEW, PROBLEM_CREATE, PROBLEM_EDIT,
        IMMUNIZATION_VIEW, IMMUNIZATION_CREATE,
        FOLLOWUP_CREATE, FOLLOWUP_VIEW, FOLLOWUP_COMPLETE,
        RECONCILIATION_VIEW, INTERVENTION_VIEW,
        NURSING_RISK_VIEW, NURSING_RISK_CREATE,
        ORDER_SET_VIEW, ORDER_SET_CREATE, ORDER_SET_EDIT,
        TEMPLATE_VIEW, TEMPLATE_CREATE, TEMPLATE_EDIT,
        INBOX_VIEW, RESULT_ACK, REMINDER_VIEW, REMINDER_ACK,
        CLINICAL_SUMMARY_VIEW,
    ],
    'SuperAdmin': [
        PATIENT_VIEW, PATIENT_EDIT, MEDICAL_RECORD_VIEW, MEDICAL_RECORD_EDIT,
        LAB_RESULT_VIEW, LAB_RESULT_CREATE, LAB_RESULT_EDIT, LAB_RESULT_VERIFY, LAB_RESULT_AMEND,
        RADIOLOGY_VIEW, RADIOLOGY_CREATE, RADIOLOGY_EDIT, RADIOLOGY_SIGN,
        RADIOLOGY_AMEND, PRESCRIPTION_VIEW, PRESCRIPTION_CREATE, PRESCRIPTION_EDIT,
        PRESCRIPTION_CANCEL, PRESCRIPTION_DISPENSE, INVENTORY_MANAGE,
        VITALS_CREATE, VITALS_EDIT, NURSING_NOTE_CREATE,
        CARE_PLAN_CREATE, CARE_PLAN_EDIT, MEDICATION_ADMIN, INTAKE_OUTPUT_RECORD,
        BILL_VIEW, BILL_CREATE, BILL_EDIT, BILL_VOID, PAYMENT_RECORD, SERVICE_CATALOG_MANAGE,
        ADMISSION_VIEW, ADMISSION_CREATE, ADMISSION_DISCHARGE, BED_MANAGE,
        REPORT_VIEW, REPORT_EXPORT, AUDIT_VIEW,
        ADMIN_MANAGE_USERS, ADMIN_MANAGE_ROLES, ADMIN_MANAGE_PERMISSIONS,
        PATIENT_DOCUMENT_VIEW, PATIENT_DOCUMENT_UPLOAD, PATIENT_DOCUMENT_DELETE,
        AI_USE, MEDICATION_REVIEW, DRUG_INTERACTION, AI_IMAGE_ANALYSIS,
        TIMELINE_VIEW, ALERT_VIEW, ALERT_ACK, ALERTS_MANAGE, SEARCH_GLOBAL,
        ALLERGY_VIEW, ALLERGY_CREATE, ALLERGY_EDIT,
        PROBLEM_VIEW, PROBLEM_CREATE, PROBLEM_EDIT,
        IMMUNIZATION_VIEW, IMMUNIZATION_CREATE,
        FOLLOWUP_CREATE, FOLLOWUP_VIEW, FOLLOWUP_COMPLETE,
        RECONCILIATION_VIEW, RECONCILIATION_CREATE, RECONCILIATION_COMPLETE,
        INTERVENTION_CREATE, INTERVENTION_VIEW, INTERVENTION_RESPOND,
        NURSING_RISK_VIEW, NURSING_RISK_CREATE,
        ORDER_SET_VIEW, ORDER_SET_CREATE, ORDER_SET_EDIT,
        TEMPLATE_VIEW, TEMPLATE_CREATE, TEMPLATE_EDIT,
        INBOX_VIEW, RESULT_ACK, REMINDER_VIEW, REMINDER_ACK,
        CLINICAL_SUMMARY_VIEW,
    ],
}


def seed_permissions(db):
    """Create Permission rows and assign them to the default roles.

    Safe to call repeatedly (idempotent). Returns (created_permissions,
    assigned_links) counts for logging.
    """
    from app.models import Role, Permission
    created = 0
    assigned = 0
    all_names = set()
    for names in ROLE_PERMISSIONS.values():
        all_names.update(names)
    for name in all_names:
        perm = Permission.query.filter_by(name=name).first()
        if perm is None:
            perm = Permission(name=name)
            db.session.add(perm)
            created += 1
    db.session.flush()
    for role_name, perm_names in ROLE_PERMISSIONS.items():
        role = Role.query.filter_by(name=role_name).first()
        if role is None:
            continue
        for pname in perm_names:
            perm = Permission.query.filter_by(name=pname).first()
            if perm and perm not in role.permissions:
                role.permissions.append(perm)
                assigned += 1
    db.session.commit()
    return created, assigned
