"""Granular, record-level permission catalog for iHIS Core.

The system the project is moving toward is:

    User -> Role -> Permissions -> Resource -> (Patient / Department / Specialty)

Instead of checking a role name on a page, routes should check a *permission*
on a *record type*, with ownership/specialty as an additional gate. This module
defines the canonical permission names and seeds them onto the matching roles.

Permission naming convention:  <RESOURCE>_<ACTION>
Actions: VIEW, CREATE, EDIT, VERIFY, SIGN, AMEND, DISPENSE, DELETE, MANAGE
"""

# ---- Patients / demographics ----
PATIENT_VIEW = 'PATIENT_VIEW'
PATIENT_CREATE = 'PATIENT_CREATE'
PATIENT_EDIT = 'PATIENT_EDIT'

# ---- Medical records (doctor-owned) ----
MEDICAL_RECORD_VIEW = 'MEDICAL_RECORD_VIEW'
MEDICAL_RECORD_CREATE = 'MEDICAL_RECORD_CREATE'
MEDICAL_RECORD_EDIT = 'MEDICAL_RECORD_EDIT'
MEDICAL_RECORD_SIGN = 'MEDICAL_RECORD_SIGN'
MEDICAL_RECORD_AMEND = 'MEDICAL_RECORD_AMEND'

# ---- Lab ----
LAB_ORDER_VIEW = 'LAB_ORDER_VIEW'
LAB_ORDER_CREATE = 'LAB_ORDER_CREATE'
LAB_RESULT_VIEW = 'LAB_RESULT_VIEW'
LAB_RESULT_CREATE = 'LAB_RESULT_CREATE'
LAB_RESULT_EDIT = 'LAB_RESULT_EDIT'
LAB_RESULT_VERIFY = 'LAB_RESULT_VERIFY'
LAB_RESULT_AMEND = 'LAB_RESULT_AMEND'

# ---- Radiology ----
RADIOLOGY_ORDER_VIEW = 'RADIOLOGY_ORDER_VIEW'
RADIOLOGY_ORDER_CREATE = 'RADIOLOGY_ORDER_CREATE'
RADIOLOGY_STUDY_VIEW = 'RADIOLOGY_STUDY_VIEW'
RADIOLOGY_VIEW = 'RADIOLOGY_VIEW'
RADIOLOGY_CREATE = 'RADIOLOGY_CREATE'
RADIOLOGY_EDIT = 'RADIOLOGY_EDIT'
RADIOLOGY_SIGN = 'RADIOLOGY_SIGN'
RADIOLOGY_AMEND = 'RADIOLOGY_AMEND'

# ---- Prescriptions ----
PRESCRIPTION_VIEW = 'PRESCRIPTION_VIEW'
PRESCRIPTION_CREATE = 'PRESCRIPTION_CREATE'
PRESCRIPTION_EDIT = 'PRESCRIPTION_EDIT'
PRESCRIPTION_CANCEL = 'PRESCRIPTION_CANCEL'
PRESCRIPTION_DISPENSE = 'PRESCRIPTION_DISPENSE'

# ---- Pharmacy inventory ----
PHARMACY_INVENTORY_VIEW = 'PHARMACY_INVENTORY_VIEW'
PHARMACY_INVENTORY_CREATE = 'PHARMACY_INVENTORY_CREATE'
PHARMACY_INVENTORY_EDIT = 'PHARMACY_INVENTORY_EDIT'
PHARMACY_STOCK_ADJUST = 'PHARMACY_STOCK_ADJUST'
INVENTORY_MANAGE = 'INVENTORY_MANAGE'

# ---- Nursing ----
VITALS_VIEW = 'VITALS_VIEW'
VITALS_CREATE = 'VITALS_CREATE'
VITALS_EDIT = 'VITALS_EDIT'
NURSING_NOTE_CREATE = 'NURSING_NOTE_CREATE'
CARE_PLAN_CREATE = 'CARE_PLAN_CREATE'
CARE_PLAN_EDIT = 'CARE_PLAN_EDIT'
MEDICATION_ADMIN = 'MEDICATION_ADMIN'
INTAKE_OUTPUT_RECORD = 'INTAKE_OUTPUT_RECORD'

# ---- Dentistry ----
DENTAL_RECORD_VIEW = 'DENTAL_RECORD_VIEW'
DENTAL_RECORD_CREATE = 'DENTAL_RECORD_CREATE'
DENTAL_RECORD_EDIT = 'DENTAL_RECORD_EDIT'

# ---- Physiotherapy ----
PHYSIO_ASSESSMENT_VIEW = 'PHYSIO_ASSESSMENT_VIEW'
PHYSIO_ASSESSMENT_CREATE = 'PHYSIO_ASSESSMENT_CREATE'
PHYSIO_ASSESSMENT_EDIT = 'PHYSIO_ASSESSMENT_EDIT'

# ---- Reports / audit / system ----
REPORT_VIEW = 'REPORT_VIEW'
REPORT_EXPORT = 'REPORT_EXPORT'
AUDIT_VIEW = 'AUDIT_VIEW'
ADMIN_MANAGE_USERS = 'ADMIN_MANAGE_USERS'
ADMIN_MANAGE_ROLES = 'ADMIN_MANAGE_ROLES'
ADMIN_MANAGE_PERMISSIONS = 'ADMIN_MANAGE_PERMISSIONS'

# ---- Billing ----
BILL_VIEW = 'BILL_VIEW'
BILL_CREATE = 'BILL_CREATE'
BILL_EDIT = 'BILL_EDIT'
BILL_VOID = 'BILL_VOID'
PAYMENT_RECORD = 'PAYMENT_RECORD'
SERVICE_CATALOG_MANAGE = 'SERVICE_CATALOG_MANAGE'

# ---- Admissions & Beds ----
ADMISSION_VIEW = 'ADMISSION_VIEW'
ADMISSION_CREATE = 'ADMISSION_CREATE'
ADMISSION_DISCHARGE = 'ADMISSION_DISCHARGE'
BED_MANAGE = 'BED_MANAGE'

# Map each permission to the role(s) that should hold it by default.
ROLE_PERMISSIONS = {
    'Doctor': [
        PATIENT_VIEW, MEDICAL_RECORD_VIEW, MEDICAL_RECORD_CREATE, MEDICAL_RECORD_EDIT,
        MEDICAL_RECORD_SIGN, MEDICAL_RECORD_AMEND,
        LAB_ORDER_VIEW, LAB_ORDER_CREATE, LAB_RESULT_VIEW,
        RADIOLOGY_ORDER_VIEW, RADIOLOGY_ORDER_CREATE, RADIOLOGY_STUDY_VIEW, RADIOLOGY_VIEW,
        PRESCRIPTION_VIEW, PRESCRIPTION_CREATE, PRESCRIPTION_EDIT, PRESCRIPTION_CANCEL,
        ADMISSION_VIEW,
    ],
    'LabTechnician': [
        PATIENT_VIEW, LAB_ORDER_VIEW, LAB_RESULT_VIEW, LAB_RESULT_CREATE, LAB_RESULT_EDIT,
        LAB_RESULT_VERIFY, LAB_RESULT_AMEND,
    ],
    'Radiologist': [
        PATIENT_VIEW, RADIOLOGY_ORDER_VIEW, RADIOLOGY_STUDY_VIEW, RADIOLOGY_VIEW,
        RADIOLOGY_CREATE, RADIOLOGY_EDIT, RADIOLOGY_SIGN, RADIOLOGY_AMEND,
    ],
    'Pharmacist': [
        PATIENT_VIEW, PRESCRIPTION_VIEW, PRESCRIPTION_DISPENSE,
        PHARMACY_INVENTORY_VIEW, PHARMACY_INVENTORY_CREATE, PHARMACY_INVENTORY_EDIT,
        PHARMACY_STOCK_ADJUST, INVENTORY_MANAGE,
    ],
    'Nurse': [
        PATIENT_VIEW, MEDICAL_RECORD_VIEW, LAB_RESULT_VIEW, RADIOLOGY_VIEW,
        PRESCRIPTION_VIEW, VITALS_VIEW, VITALS_CREATE, VITALS_EDIT, NURSING_NOTE_CREATE,
        CARE_PLAN_CREATE, CARE_PLAN_EDIT, MEDICATION_ADMIN, INTAKE_OUTPUT_RECORD,
        ADMISSION_VIEW,
    ],
    'Receptionist': [
        PATIENT_VIEW, PATIENT_CREATE, PATIENT_EDIT,
        BILL_VIEW, BILL_CREATE, BILL_EDIT, PAYMENT_RECORD,
        ADMISSION_VIEW, ADMISSION_CREATE,
    ],
    'Dentist': [
        PATIENT_VIEW, DENTAL_RECORD_VIEW, DENTAL_RECORD_CREATE, DENTAL_RECORD_EDIT,
    ],
    'Physiotherapist': [
        PATIENT_VIEW, PHYSIO_ASSESSMENT_VIEW, PHYSIO_ASSESSMENT_CREATE, PHYSIO_ASSESSMENT_EDIT,
    ],
    'Admin': [
        PATIENT_VIEW, MEDICAL_RECORD_VIEW, LAB_RESULT_VIEW, RADIOLOGY_VIEW,
        PRESCRIPTION_VIEW, INVENTORY_MANAGE,
        MEDICATION_ADMIN, INTAKE_OUTPUT_RECORD,
        BILL_VIEW, BILL_CREATE, BILL_EDIT, BILL_VOID, PAYMENT_RECORD, SERVICE_CATALOG_MANAGE,
        ADMISSION_VIEW, ADMISSION_CREATE, ADMISSION_DISCHARGE, BED_MANAGE,
        REPORT_VIEW, REPORT_EXPORT, ADMIN_MANAGE_USERS,
    ],
    'SuperAdmin': [
        PATIENT_VIEW, PATIENT_EDIT, MEDICAL_RECORD_VIEW, MEDICAL_RECORD_EDIT,
        LAB_RESULT_VIEW, LAB_RESULT_CREATE, LAB_RESULT_EDIT, LAB_RESULT_VERIFY, LAB_RESULT_AMEND,
        RADIOLOGY_VIEW, RADIOLOGY_CREATE, RADIOLOGY_EDIT, RADIOLOGY_SIGN,
        RADIOLOGY_AMEND, PRESCRIPTION_VIEW, PRESCRIPTION_CREATE, PRESCRIPTION_EDIT,
        PRESCRIPTION_CANCEL, PRESCRIPTION_DISPENSE, INVENTORY_MANAGE,
        VITALS_CREATE, VITALS_EDIT, NURSING_NOTE_CREATE,
        CARE_PLAN_CREATE, CARE_PLAN_EDIT, MEDICATION_ADMIN, INTAKE_OUTPUT_RECORD,
        BILL_VIEW, BILL_CREATE, BILL_EDIT, BILL_VOID, PAYMENT_RECORD, SERVICE_CATALOG_MANAGE,
        ADMISSION_VIEW, ADMISSION_CREATE, ADMISSION_DISCHARGE, BED_MANAGE,
        REPORT_VIEW, REPORT_EXPORT, AUDIT_VIEW,
        ADMIN_MANAGE_USERS, ADMIN_MANAGE_ROLES, ADMIN_MANAGE_PERMISSIONS,
    ],
}


def seed_permissions(db):
    """Create Permission rows and assign them to the default roles.

    Safe to call repeatedly (idempotent). Returns (created_permissions,
    assigned_links) counts for logging.
    """
    from app.models import Role, Permission
    created = 0
    assigned = 0
    all_names = set()
    for names in ROLE_PERMISSIONS.values():
        all_names.update(names)
    for name in all_names:
        perm = Permission.query.filter_by(name=name).first()
        if perm is None:
            perm = Permission(name=name)
            db.session.add(perm)
            created += 1
    db.session.flush()
    for role_name, perm_names in ROLE_PERMISSIONS.items():
        role = Role.query.filter_by(name=role_name).first()
        if role is None:
            continue
        for pname in perm_names:
            perm = Permission.query.filter_by(name=pname).first()
            if perm and perm not in role.permissions:
                role.permissions.append(perm)
                assigned += 1
    db.session.commit()
    return created, assigned
