"""index_clinical_hot_path_fk_columns

Revision ID: 59f96da6bbf3
Revises: 12a33945697d
Create Date: 2026-09-02 21:51:41.131926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f96da6bbf3'
down_revision = '12a33945697d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_doctor_id'), ['doctor_id'], unique=False)

    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_items_bill_id'), ['bill_id'], unique=False)

    with op.batch_alter_table('dental_charts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dental_charts_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('dental_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dental_images_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('dental_procedures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dental_procedures_dentist_id'), ['dentist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dental_procedures_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dental_procedures_treatment_plan_id'), ['treatment_plan_id'], unique=False)

    with op.batch_alter_table('dental_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dental_records_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('dental_treatment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dental_treatment_plans_dentist_id'), ['dentist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dental_treatment_plans_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnoses_doctor_id'), ['doctor_id'], unique=False)

    with op.batch_alter_table('dispensing_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispensing_records_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispensing_records_pharmacist_id'), ['pharmacist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispensing_records_prescription_id'), ['prescription_id'], unique=False)

    with op.batch_alter_table('functional_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_functional_outcomes_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_orders_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_test_id'), ['test_id'], unique=False)

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_records_doctor_id'), ['doctor_id'], unique=False)

    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_administrations_medication_id'), ['medication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_administrations_prescription_id'), ['prescription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_administrations_prescription_item_id'), ['prescription_item_id'], unique=False)

    with op.batch_alter_table('orthodontic_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orthodontic_cases_dentist_id'), ['dentist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orthodontic_cases_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_bill_id'), ['bill_id'], unique=False)

    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_items_medication_id'), ['medication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescription_items_prescription_id'), ['prescription_id'], unique=False)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_doctor_id'), ['doctor_id'], unique=False)

    with op.batch_alter_table('radiology_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radiology_orders_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radiology_orders_imaging_type_id'), ['imaging_type_id'], unique=False)

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_from_doctor_id'), ['from_doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_to_doctor_id'), ['to_doctor_id'], unique=False)

    with op.batch_alter_table('rehabilitation_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rehabilitation_progress_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rehabilitation_progress_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rehabilitation_progress_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('therapy_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_therapy_assessments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_therapy_assessments_therapist_id'), ['therapist_id'], unique=False)

    with op.batch_alter_table('therapy_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_therapy_plans_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_therapy_plans_therapist_id'), ['therapist_id'], unique=False)

    with op.batch_alter_table('therapy_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_therapy_sessions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_therapy_sessions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_therapy_sessions_therapist_id'), ['therapist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapy_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_therapy_sessions_therapist_id'))
        batch_op.drop_index(batch_op.f('ix_therapy_sessions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_therapy_sessions_patient_id'))

    with op.batch_alter_table('therapy_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_therapy_plans_therapist_id'))
        batch_op.drop_index(batch_op.f('ix_therapy_plans_patient_id'))

    with op.batch_alter_table('therapy_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_therapy_assessments_therapist_id'))
        batch_op.drop_index(batch_op.f('ix_therapy_assessments_patient_id'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_created_by'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_to'))

    with op.batch_alter_table('rehabilitation_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rehabilitation_progress_session_id'))
        batch_op.drop_index(batch_op.f('ix_rehabilitation_progress_plan_id'))
        batch_op.drop_index(batch_op.f('ix_rehabilitation_progress_patient_id'))

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_to_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_from_doctor_id'))

    with op.batch_alter_table('radiology_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radiology_orders_imaging_type_id'))
        batch_op.drop_index(batch_op.f('ix_radiology_orders_doctor_id'))

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_doctor_id'))

    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_items_prescription_id'))
        batch_op.drop_index(batch_op.f('ix_prescription_items_medication_id'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_bill_id'))

    with op.batch_alter_table('orthodontic_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orthodontic_cases_patient_id'))
        batch_op.drop_index(batch_op.f('ix_orthodontic_cases_dentist_id'))

    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_administrations_prescription_item_id'))
        batch_op.drop_index(batch_op.f('ix_medication_administrations_prescription_id'))
        batch_op.drop_index(batch_op.f('ix_medication_administrations_medication_id'))

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_records_doctor_id'))

    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_orders_test_id'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_doctor_id'))

    with op.batch_alter_table('functional_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_functional_outcomes_patient_id'))

    with op.batch_alter_table('dispensing_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispensing_records_prescription_id'))
        batch_op.drop_index(batch_op.f('ix_dispensing_records_pharmacist_id'))
        batch_op.drop_index(batch_op.f('ix_dispensing_records_item_id'))

    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnoses_doctor_id'))

    with op.batch_alter_table('dental_treatment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dental_treatment_plans_patient_id'))
        batch_op.drop_index(batch_op.f('ix_dental_treatment_plans_dentist_id'))

    with op.batch_alter_table('dental_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dental_records_patient_id'))

    with op.batch_alter_table('dental_procedures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dental_procedures_treatment_plan_id'))
        batch_op.drop_index(batch_op.f('ix_dental_procedures_patient_id'))
        batch_op.drop_index(batch_op.f('ix_dental_procedures_dentist_id'))

    with op.batch_alter_table('dental_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dental_images_patient_id'))

    with op.batch_alter_table('dental_charts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dental_charts_patient_id'))

    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_items_bill_id'))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_doctor_id'))

    # ### end Alembic commands ###
