"""index patient FKs and enforce boolean not-null

Revision ID: 6e4b0dc64295
Revises: ed88d1bd7e4b
Create Date: 2026-09-02 16:01:13.381188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4b0dc64295'
down_revision = 'ed88d1bd7e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.alter_column('is_applied',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('care_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_care_plans_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('care_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_care_teams_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_diagnoses_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('intake_output', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intake_output_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_orders_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.alter_column('is_abnormal',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_critical',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('lab_test_catalog', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.alter_column('successful',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_records_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_administrations_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('nursing_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nursing_notes_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_documents_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('radiology_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radiology_orders_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('service_catalog', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('therapy_sessions', schema=None) as batch_op:
        batch_op.alter_column('followup_required',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vital_signs_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vital_signs_patient_id'))

    with op.batch_alter_table('therapy_sessions', schema=None) as batch_op:
        batch_op.alter_column('followup_required',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_patient_id'))

    with op.batch_alter_table('service_catalog', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_patient_id'))

    with op.batch_alter_table('radiology_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radiology_orders_patient_id'))

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_patient_id'))

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_documents_patient_id'))

    with op.batch_alter_table('nursing_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nursing_notes_patient_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_administrations_patient_id'))

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_records_patient_id'))

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.alter_column('successful',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('lab_test_catalog', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.alter_column('is_critical',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_abnormal',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_orders_patient_id'))

    with op.batch_alter_table('intake_output', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intake_output_patient_id'))

    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnoses_patient_id'))
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('care_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_teams_patient_id'))

    with op.batch_alter_table('care_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_plans_patient_id'))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_patient_id'))
        batch_op.alter_column('is_applied',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
