"""add patient department

Revision ID: 8a75a265845d
Revises: 59f96da6bbf3
Create Date: 2026-09-05 15:57:41.828421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a75a265845d'
down_revision = '59f96da6bbf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_department_id'), ['department_id'], unique=False)
        batch_op.create_foreign_key('fk_patients_department_id', 'departments',
                                    ['department_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patients_department_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_patients_department_id'))
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
