"""timeline alerts reconciliation pharmacy interventions

Revision ID: a0b299aeba56
Revises: d95375ed9481
Create Date: 2026-09-01 21:42:33.243857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b299aeba56'
down_revision = 'd95375ed9481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # New clinical-model tables. These were created locally via create_all() so
    # autogenerate only emitted ALTERs; production still needs CREATE TABLE, so
    # we add the DDL explicitly (guarded by a no-op when the tables already exist).
    op.create_table(
        'timeline_events',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('patient_id', sa.Integer(), sa.ForeignKey('patients.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=250), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('occurred_at', sa.DateTime(), nullable=True),
        sa.Column('source_type', sa.String(length=50), nullable=True),
        sa.Column('source_id', sa.Integer(), nullable=True),
        sa.Column('department', sa.String(length=100), nullable=True),
        sa.Column('created_by', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table(
        'clinical_alerts',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('patient_id', sa.Integer(), sa.ForeignKey('patients.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('alert_type', sa.String(length=50), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=True),
        sa.Column('title', sa.String(length=250), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('acknowledged_by', sa.Integer(), nullable=True),
        sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
        sa.Column('resolved_by', sa.Integer(), nullable=True),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.Column('resolved_note', sa.Text(), nullable=True),
        sa.Column('source_type', sa.String(length=50), nullable=True),
        sa.Column('source_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    )
    with op.batch_alter_table('clinical_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_alerts_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_alerts_created_at'), ['created_at'], unique=False)

    op.create_table(
        'allergies',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('patient_id', sa.Integer(), sa.ForeignKey('patients.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('substance', sa.String(length=200), nullable=False),
        sa.Column('reaction', sa.String(length=250), nullable=True),
        sa.Column('severity', sa.String(length=20), nullable=True),
        sa.Column('onset', sa.String(length=100), nullable=True),
        sa.Column('verified', sa.Boolean(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('recorded_by', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
    )
    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allergies_patient_id'), ['patient_id'], unique=False)

    op.create_table(
        'problems',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('patient_id', sa.Integer(), sa.ForeignKey('patients.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('icd10_code', sa.String(length=20), nullable=True),
        sa.Column('description', sa.String(length=300), nullable=False),
        sa.Column('onset', sa.Date(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('severity', sa.String(length=20), nullable=True),
        sa.Column('resolved_date', sa.Date(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('recorded_by', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
    )
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problems_patient_id'), ['patient_id'], unique=False)

    op.create_table(
        'immunization_records',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('patient_id', sa.Integer(), sa.ForeignKey('patients.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('vaccine_name', sa.String(length=150), nullable=False),
        sa.Column('dose_number', sa.Integer(), nullable=True),
        sa.Column('administered_at', sa.DateTime(), nullable=True),
        sa.Column('lot_number', sa.String(length=50), nullable=True),
        sa.Column('site', sa.String(length=50), nullable=True),
        sa.Column('administered_by', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('next_due', sa.Date(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
    )
    with op.batch_alter_table('immunization_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_immunization_records_patient_id'), ['patient_id'], unique=False)

    op.create_table(
        'follow_ups',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('patient_id', sa.Integer(), sa.ForeignKey('patients.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('provider_id', sa.Integer(), sa.ForeignKey('doctors.id'), nullable=True),
        sa.Column('scheduled_for', sa.DateTime(), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_by', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
    )
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_ups_patient_id'), ['patient_id'], unique=False)

    op.create_table(
        'nursing_risk_assessments',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('patient_id', sa.Integer(), sa.ForeignKey('patients.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('nurse_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('assessment_type', sa.String(length=50), nullable=True),
        sa.Column('score', sa.Integer(), nullable=True),
        sa.Column('risk_level', sa.String(length=20), nullable=True),
        sa.Column('factors', sa.Text(), nullable=True),
        sa.Column('recommendations', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('assessed_at', sa.DateTime(), nullable=True),
    )
    with op.batch_alter_table('nursing_risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nursing_risk_assessments_patient_id'), ['patient_id'], unique=False)

    op.create_table(
        'medication_reconciliations',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('patient_id', sa.Integer(), sa.ForeignKey('patients.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('pharmacist_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('admission_id', sa.Integer(), sa.ForeignKey('admissions.id', ondelete='SET NULL'), nullable=True),
        sa.Column('reconciliation_type', sa.String(length=30), nullable=True),
        sa.Column('home_medications', sa.Text(), nullable=True),
        sa.Column('active_prescriptions', sa.Text(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
    )
    with op.batch_alter_table('medication_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_reconciliations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_reconciliations_status'), ['status'], unique=False)

    op.create_table(
        'reconciliation_discrepancies',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('reconciliation_id', sa.Integer(),
                  sa.ForeignKey('medication_reconciliations.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('medication_id', sa.Integer(), sa.ForeignKey('medications.id'), nullable=True),
        sa.Column('discrepancy_type', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('severity', sa.String(length=20), nullable=True),
        sa.Column('recommended_action', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('resolved_note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
    )

    op.create_table(
        'pharmacy_interventions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('patient_id', sa.Integer(), sa.ForeignKey('patients.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('prescription_id', sa.Integer(), sa.ForeignKey('prescriptions.id', ondelete='SET NULL'), nullable=True),
        sa.Column('pharmacist_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('prescriber_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('issue', sa.Text(), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=True),
        sa.Column('recommendation', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('response', sa.Text(), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
    )
    with op.batch_alter_table('pharmacy_interventions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pharmacy_interventions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacy_interventions_status'), ['status'], unique=False)

    with op.batch_alter_table('drug_interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mechanism', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('management', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_drug_interaction_pair', ['medication_a_id', 'medication_b_id'])

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_patient_documents_uploaded_by', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urgency', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('response_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_referrals_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_referrals_reviewed_by', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_referrals_created_by', 'users', ['created_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_referrals_created_by', type_='foreignkey')
        batch_op.drop_constraint('fk_referrals_reviewed_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_referrals_status'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('response_date')
        batch_op.drop_column('response')
        batch_op.drop_column('notes')
        batch_op.drop_column('urgency')

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patient_documents_uploaded_by', type_='foreignkey')
        batch_op.drop_column('notes')
        batch_op.drop_column('category')
        batch_op.drop_column('uploaded_by')

    with op.batch_alter_table('drug_interactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_drug_interaction_pair', type_='unique')
        batch_op.drop_column('management')
        batch_op.drop_column('mechanism')

    op.drop_table('pharmacy_interventions')
    op.drop_table('reconciliation_discrepancies')
    op.drop_table('medication_reconciliations')
    op.drop_table('nursing_risk_assessments')
    op.drop_table('follow_ups')
    op.drop_table('immunization_records')
    op.drop_table('problems')
    op.drop_table('allergies')
    op.drop_table('clinical_alerts')
    op.drop_table('timeline_events')

    # ### end Alembic commands ###
