"""add discharge summary fields

Revision ID: a131a27bf5e5
Revises: 12ee9a1299d2
Create Date: 2026-08-30 20:47:51.918043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a131a27bf5e5'
down_revision = '12ee9a1299d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discharge_diagnosis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('discharge_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('follow_up_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('discharge_medications', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_column('discharge_medications')
        batch_op.drop_column('follow_up_instructions')
        batch_op.drop_column('discharge_summary')
        batch_op.drop_column('discharge_diagnosis')

    # ### end Alembic commands ###
