"""Generate a new alembic migration from the current models (autogenerate).

Usage: python scripts/_gen_migration.py "add_payment_idempotency_constraint"

Runs against a scratch SQLite DB: applies the current chain to HEAD (no
db.create_all), then autogenerates the diff from HEAD -> current models.
"""
import sys
import os
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))


def main():
    msg = sys.argv[1] if len(sys.argv) > 1 else 'autogenerated_migration'
    tmp = Path(tempfile.gettempdir()) / 'ihis_miggen.db'
    if tmp.exists():
        tmp.unlink()
    dburi = 'sqlite:///' + str(tmp).replace('\\', '/')
    os.environ['DATABASE_URL'] = dburi
    os.environ['FLASK_CONFIG'] = 'development'
    os.environ['SECRET_KEY'] = 'x' * 90

    from flask import Flask
    from flask_migrate import Migrate, upgrade
    from config import config_map
    from app import db as _db
    import app.models  # noqa

    flask_app = Flask('miggen')
    flask_app.config.from_object(config_map['development'])
    flask_app.config['SQLALCHEMY_DATABASE_URI'] = dburi
    _db.init_app(flask_app)
    migrate = Migrate(flask_app, _db)  # noqa

    with flask_app.app_context():
        upgrade()  # bring scratch DB to HEAD (migrations only, no create_all)

    # Rebuild with a fresh alembic context bound to the scratch DB for autogen.
    os.environ['DATABASE_URL'] = dburi
    from alembic.config import Config
    from alembic import command
    cfg = Config(str(REPO / 'migrations' / 'alembic.ini'))
    cfg.set_main_option('script_location', str(REPO / 'migrations'))
    cfg.set_main_option('sqlalchemy.url', dburi)

    with flask_app.app_context():
        command.revision(cfg, message=msg, autogenerate=True)
    print('Migration generated.')


if __name__ == '__main__':
    main()